apiVersion: v1
kind: Service
metadata:
  name: kube-copilot-service
  namespace: kube-copilot
  labels:
    app: kube-copilot
spec:
  type: NodePort
  selector:
    app: kube-copilot
  ports:
    - port: 80
      targetPort: 8321
      nodePort: 30005
